Include detail on setting service-role as the path for S3 cross-region replication documentation
awsdocs/amazon-s3-userguide pull request #70
Opened 2022-07-14 11:21 UTC by LeeS-NakedWines

There is no mention prior to the bucket policy that if cross-account, the IAM role path MUST be /service-role/. If allowing CRR to automatically generate a role it creates this as so, but if you generate manually through console,CLI or Terraform with the correct permissions it will not work unless /service-role/ is the identifier.

*Issue #, if available:*

*Description of changes:*
Add sentence about setting /service-role/ path. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-18 09:31 UTC, LeeS-NakedWines commented
Hi @lincolahanbeck / @aws-alan is there anything else needed on my part to justify / get this merged to improve replication documentation? Thanks

2022-08-18 17:15 UTC, aws-alan requested changes
Can you please edit the second sentence such that it reads:
For more information, see [IAM Identifiers](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html) the *IAM User Guide*\.

2022-08-18 17:34 UTC, LeeS-NakedWines commented
Hi @aws-alan - absolutely, just pushed that change, as per format on line 39 for consistency. Thanks

2022-08-19 18:01 UTC, aws-alan approved these changes

2022-08-19 18:01 UTC, merged